image: composer:2.0

pipelines:
  branches:
    master:
      - step:
          name: Build Artefact
          script:
            - git archive --format=tar.gz master -o artefact.tar.gz
          artifacts:
            - artefact.tar.gz
      - step:
          name: Deploy to production
          deployment: production
          script:
            - pipe: atlassian/heroku-deploy:1.1.1
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: $HEROKU_APP_NAME
                ZIP_FILE: artefact.tar.gz
